'use strict';

/**
 * Danh mục mã quyền, đồng bộ với bảng permissions trong seed data.
 * Dùng hằng số thay vì chuỗi rời rạc để tránh gõ sai và dễ tra cứu chỗ sử dụng.
 */
const P = {
  // Người dùng
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ASSIGN_ROLE: 'USER_ASSIGN_ROLE',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  ADDRESS_MANAGE: 'ADDRESS_MANAGE',
  // Vai trò
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',
  // Gian hàng
  SHOP_VIEW: 'SHOP_VIEW',
  SHOP_CREATE: 'SHOP_CREATE',
  SHOP_UPDATE: 'SHOP_UPDATE',
  SHOP_APPROVE: 'SHOP_APPROVE',
  WAREHOUSE_MANAGE: 'WAREHOUSE_MANAGE',
  // Danh mục và sản phẩm
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_MANAGE: 'CATEGORY_MANAGE',
  BRAND_MANAGE: 'BRAND_MANAGE',
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_APPROVE: 'PRODUCT_APPROVE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
  // Đơn hàng
  CART_MANAGE: 'CART_MANAGE',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_VIEW_OWN: 'ORDER_VIEW_OWN',
  ORDER_VIEW_SHOP: 'ORDER_VIEW_SHOP',
  ORDER_VIEW_ALL: 'ORDER_VIEW_ALL',
  ORDER_UPDATE_STATUS: 'ORDER_UPDATE_STATUS',
  ORDER_CANCEL: 'ORDER_CANCEL',
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  REFUND_REQUEST: 'REFUND_REQUEST',
  REFUND_APPROVE: 'REFUND_APPROVE',
  SHIPMENT_MANAGE: 'SHIPMENT_MANAGE',
  // Hệ thống
  CONFIG_MANAGE: 'CONFIG_MANAGE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  REPORT_VIEW: 'REPORT_VIEW',
};

const ROLES = { ADMIN: 'ADMIN', SELLER: 'SELLER', MEMBER: 'MEMBER', GUEST: 'GUEST' };

module.exports = { PERMISSIONS: P, ROLES };
